export const SCENE_KEYS = {
  boot: "BootScene",
  preload: "PreloadScene",
  menu: "MainMenuScene",
  skinSelect: "SkinSelectScene",
  skillLoadout: "SkillLoadoutScene",
  stageSelect: "StageSelectScene",
  campaign: "CampaignScene",
  missions: "MissionsScene",
  leaderboard: "LeaderboardScene",
  tournament: "TournamentScene",
  profile: "ProfileScene",
  settings: "SettingsScene",
  arena: "ArenaScene",
  result: "ResultScene",
} as const;
